title: GnR
author: Chase White
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The first set of lyrics from my favorite song in high school. When life was rough, all I needed was
  a reminder, that's life in the jungle baby!
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
